question_data = [
                     {"type": "boolean", 
                      "difficulty": "hard", 
                      "category": "General Knowledge",
                      "question": "In Scandinavian languages, the letter &Aring; means river.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "hard", 
                      "category": "General Knowledge",
                      "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "A pencil&#039;s lead is typically made from graphite, not lead",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy",
                      "category": "General Knowledge",
                      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "hard", 
                      "category": "General Knowledge",
                      "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Ping-Pong originated in England", 
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "Only a small percentage of the world&#039;s population is lactose intolerant.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "The National Animal of Scotland is the Unicorn.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": 
                      "easy", "category": "General Knowledge",
                      "question": "Did Michael Jackson invent the moonwalk?", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Jingle Bells was originally meant for Thanksgiving", 
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Water is naturally coloured blue.", 
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Bulls are attracted to the color red.", 
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "hard", 
                      "category": "General Knowledge",
                      "question": "Is Luxembourgish a real language?", 
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "The CEO of tech company Apple following Steve Jobs is named Tim Apple.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "hard", 
                      "category": "General Knowledge",
                      "question": "Samhainophobia is the term used for an abnormal and persistent fear of halloween.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "An eggplant is a vegetable.", 
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "Pure water effectively conducts electricity ", 
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "The French word to travel is &quot;Travail&quot;",
                      "correct_answer": "False", 
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                      "correct_answer": "False", 
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                      "correct_answer": "False", 
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "easy", 
                      "category": "General Knowledge",
                      "question": "Adolf Hitler was born in Australia. ", 
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", 
                      "difficulty": "medium", 
                      "category": "General Knowledge",
                      "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                      "correct_answer": "True", 
                      "incorrect_answers": ["False"]}
                      ]
